require("kuwerin.plugins.aerial")
require("kuwerin.plugins.bufferline")
require("kuwerin.plugins.lspconfig")
require("kuwerin.plugins.cmp")
require("kuwerin.plugins.neotree")
require("kuwerin.plugins.noice")
require("kuwerin.plugins.nvim-web-devicons")
